### ISSUE TITLE
scoverage during runtime?

### ISSUE THREAD

**Issue by dbathily** [nafg/slick-migration-api#5]
Hi, 

Got this exception when I use the api :

```
java.lang.NoClassDefFoundError: scoverage/Invoker$
        at scala.slick.migration.api.TableMigration$.apply(TableMigration.scala:80) ~[slick-migration-api_2.11-0.1.jar:0.1]
        at db.migration.defaultdb.V1__001_Init.slick_migrate(V1__001_Init.scala:15) ~[na:na]
        at db.migration.SlickMigration$$anonfun$migrate$1.apply$mcV$sp(SlickMigration.scala:30) ~[na:na]
        at db.migration.SlickMigration$$anonfun$migrate$1.apply(SlickMigration.scala:30) ~[na:na]
        at db.migration.SlickMigration$$anonfun$migrate$1.apply(SlickMigration.scala:30) ~[na:na]
Caused by: java.lang.ClassNotFoundException: scoverage.Invoker$
        at java.net.URLClassLoader$1.run(URLClassLoader.java:366) ~[na:1.7.0_17]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355) ~[na:1.7.0_17]
        at java.security.AccessController.doPrivileged(Native Method) ~[na:1.7.0_17]
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354) ~[na:1.7.0_17]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:423) ~[na:1.7.0_17]
```

**Comment by nafg** [comment]
Ouch! Now that you mention it I think I may have hit that, without realizing what was happening. I guess the culprit is this: https://github.com/nafg/slick-migration-api/blob/master/.travis.yml#L2

I didn't realize scoverage would have that effect. I have to figure out how to split it into two commands in travis (if you know PR welcome)...

Thanks

**Comment by dbathily** [comment]
That was quick. Eager to test a release

**Comment by nafg** [comment]
0.1.1 on its way: https://travis-ci.org/nafg/slick-migration-api/builds/59931795

**Comment by nafg** [comment]
@dbathily done, published to http://dl.bintray.com/naftoligug/maven

**Comment by dbathily** [comment]
Thank you. It's fixed
